# -*- restclient -*-

:base-url = https://localhost:8443
:ssl-verify = nil
:headers =  <<
Content-Type: application/json

# API Testing Examples

## Get all phrases
GET :base-url/phrase
:headers

###

:phrase = POST

## Get a specific phrase
GET :base-url/phrase/POST
:headers

###

## Create a new phrase
POST :base-url/phrase/test
:headers

{
    "phrase": "test",
    "terms": ["HPE", "Test"],
    "last_update": "2024-03-25 16:02:49",
    "complexity": 0.4,
    "topics": ["Test"],
    "explanations": [
      {
        "definition": "Test is a foo that is also a bar",
        "author": "Matthew Battagel",
        "tags": ["Test"],
        "code": ["code_t", "test_t"],
        "references": [
          "<a href=https://en.wikipedia.org/wiki/test>Wikipedia link</a>"
        ],
        "heat": 3
      },
      {
        "definition": "Test is a foo that is also a bar",
        "author": "Matthew Battagel",
        "tags": ["Test"],
        "code": ["code_t", "test_t"],
        "references": [
          "<a href=https://en.wikipedia.org/wiki/test>Wikipedia link</a>"
        ],
        "heat": 3
      }
    ]
  }
}

###

## Update a phrase
PUT :base-url/phrase/test
:headers

{
  "phrase": "test",
  "terms": [
    "HPE"
  ],
  "last_update": "2023-12-19 16:12:43",
  "complexity": 0,
  "topic": [],
  "explanations": [
    {
      "definition": "test phrase for debug",
      "tags": [],
      "code": [],
      "references": [
        "<a href=https://en.wikipedia.org/wiki/test>Wikipedia link</a>"
      ],
      "heat": 0
    }
  ]
}

###

## Delete a phrase
DELETE :base-url/phrase/test

###
